// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProtoc.proto

package com.opdar.seed.io.protocol;

public final class MessageProtoc {
  private MessageProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.opdar.seed.io.protocol.Action)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.opdar.seed.io.protocol.Action.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.opdar.seed.io.protocol.Action.Type type = 1;</code>
     */
    com.opdar.seed.io.protocol.MessageProtoc.Action.Type getType();

    /**
     * <code>required string messageId = 2;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required string messageId = 2;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>required string messageId = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();
  }
  /**
   * Protobuf type {@code com.opdar.seed.io.protocol.Action}
   */
  public static final class Action extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.opdar.seed.io.protocol.Action)
      ActionOrBuilder {
    // Use Action.newBuilder() to construct.
    private Action(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Action(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Action defaultInstance;
    public static Action getDefaultInstance() {
      return defaultInstance;
    }

    public Action getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Action(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.opdar.seed.io.protocol.MessageProtoc.Action.Type value = com.opdar.seed.io.protocol.MessageProtoc.Action.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              messageId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opdar.seed.io.protocol.MessageProtoc.internal_static_com_opdar_seed_io_protocol_Action_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opdar.seed.io.protocol.MessageProtoc.internal_static_com_opdar_seed_io_protocol_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.opdar.seed.io.protocol.MessageProtoc.Action.class, com.opdar.seed.io.protocol.MessageProtoc.Action.Builder.class);
    }

    public static com.google.protobuf.Parser<Action> PARSER =
        new com.google.protobuf.AbstractParser<Action>() {
      public Action parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Action(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Action> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.opdar.seed.io.protocol.Action.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MSG = 1;</code>
       */
      MSG(0, 1),
      /**
       * <code>INQUEUE = 2;</code>
       */
      INQUEUE(1, 2),
      /**
       * <code>HEARTBEAT = 3;</code>
       */
      HEARTBEAT(2, 3),
      ;

      /**
       * <code>MSG = 1;</code>
       */
      public static final int MSG_VALUE = 1;
      /**
       * <code>INQUEUE = 2;</code>
       */
      public static final int INQUEUE_VALUE = 2;
      /**
       * <code>HEARTBEAT = 3;</code>
       */
      public static final int HEARTBEAT_VALUE = 3;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return MSG;
          case 2: return INQUEUE;
          case 3: return HEARTBEAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.opdar.seed.io.protocol.MessageProtoc.Action.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.opdar.seed.io.protocol.Action.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.opdar.seed.io.protocol.MessageProtoc.Action.Type type_;
    /**
     * <code>required .com.opdar.seed.io.protocol.Action.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.opdar.seed.io.protocol.Action.Type type = 1;</code>
     */
    public com.opdar.seed.io.protocol.MessageProtoc.Action.Type getType() {
      return type_;
    }

    public static final int MESSAGEID_FIELD_NUMBER = 2;
    private java.lang.Object messageId_;
    /**
     * <code>required string messageId = 2;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string messageId = 2;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string messageId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = com.opdar.seed.io.protocol.MessageProtoc.Action.Type.MSG;
      messageId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.opdar.seed.io.protocol.MessageProtoc.Action parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opdar.seed.io.protocol.MessageProtoc.Action prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.opdar.seed.io.protocol.Action}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.opdar.seed.io.protocol.Action)
        com.opdar.seed.io.protocol.MessageProtoc.ActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opdar.seed.io.protocol.MessageProtoc.internal_static_com_opdar_seed_io_protocol_Action_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opdar.seed.io.protocol.MessageProtoc.internal_static_com_opdar_seed_io_protocol_Action_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.opdar.seed.io.protocol.MessageProtoc.Action.class, com.opdar.seed.io.protocol.MessageProtoc.Action.Builder.class);
      }

      // Construct using com.opdar.seed.io.protocol.MessageProtoc.Action.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.opdar.seed.io.protocol.MessageProtoc.Action.Type.MSG;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opdar.seed.io.protocol.MessageProtoc.internal_static_com_opdar_seed_io_protocol_Action_descriptor;
      }

      public com.opdar.seed.io.protocol.MessageProtoc.Action getDefaultInstanceForType() {
        return com.opdar.seed.io.protocol.MessageProtoc.Action.getDefaultInstance();
      }

      public com.opdar.seed.io.protocol.MessageProtoc.Action build() {
        com.opdar.seed.io.protocol.MessageProtoc.Action result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.opdar.seed.io.protocol.MessageProtoc.Action buildPartial() {
        com.opdar.seed.io.protocol.MessageProtoc.Action result = new com.opdar.seed.io.protocol.MessageProtoc.Action(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageId_ = messageId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opdar.seed.io.protocol.MessageProtoc.Action) {
          return mergeFrom((com.opdar.seed.io.protocol.MessageProtoc.Action)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.opdar.seed.io.protocol.MessageProtoc.Action other) {
        if (other == com.opdar.seed.io.protocol.MessageProtoc.Action.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMessageId()) {
          bitField0_ |= 0x00000002;
          messageId_ = other.messageId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasMessageId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.opdar.seed.io.protocol.MessageProtoc.Action parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.opdar.seed.io.protocol.MessageProtoc.Action) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.opdar.seed.io.protocol.MessageProtoc.Action.Type type_ = com.opdar.seed.io.protocol.MessageProtoc.Action.Type.MSG;
      /**
       * <code>required .com.opdar.seed.io.protocol.Action.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.opdar.seed.io.protocol.Action.Type type = 1;</code>
       */
      public com.opdar.seed.io.protocol.MessageProtoc.Action.Type getType() {
        return type_;
      }
      /**
       * <code>required .com.opdar.seed.io.protocol.Action.Type type = 1;</code>
       */
      public Builder setType(com.opdar.seed.io.protocol.MessageProtoc.Action.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.opdar.seed.io.protocol.Action.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.opdar.seed.io.protocol.MessageProtoc.Action.Type.MSG;
        onChanged();
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <code>required string messageId = 2;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string messageId = 2;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string messageId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string messageId = 2;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string messageId = 2;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>required string messageId = 2;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        messageId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.opdar.seed.io.protocol.Action)
    }

    static {
      defaultInstance = new Action(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.opdar.seed.io.protocol.Action)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_opdar_seed_io_protocol_Action_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_opdar_seed_io_protocol_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MessageProtoc.proto\022\032com.opdar.seed.io" +
      ".protocol\"\177\n\006Action\0225\n\004type\030\001 \002(\0162\'.com." +
      "opdar.seed.io.protocol.Action.Type\022\021\n\tme" +
      "ssageId\030\002 \002(\t\"+\n\004Type\022\007\n\003MSG\020\001\022\013\n\007INQUEU" +
      "E\020\002\022\r\n\tHEARTBEAT\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_opdar_seed_io_protocol_Action_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_opdar_seed_io_protocol_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_opdar_seed_io_protocol_Action_descriptor,
        new java.lang.String[] { "Type", "MessageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
