/* Generated By:JavaCC: Do not edit this line. MapperParserConstants.java */
package com.opdar.framework.db.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MapperParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 5;
  /** RegularExpression Id. */
  int NAMESPACE = 6;
  /** RegularExpression Id. */
  int LBRACE = 7;
  /** RegularExpression Id. */
  int RBRACE = 8;
  /** RegularExpression Id. */
  int ASTERISK = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int LBRACKET = 11;
  /** RegularExpression Id. */
  int RBRACKET = 12;
  /** RegularExpression Id. */
  int DOLLER = 13;
  /** RegularExpression Id. */
  int SHARP = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int QUOTES = 17;
  /** RegularExpression Id. */
  int IDENTIFIER = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int SEMICOLON = 20;
  /** RegularExpression Id. */
  int QUOTED_STRING = 21;
  /** RegularExpression Id. */
  int DOUBLE_QUOTED = 22;
  /** RegularExpression Id. */
  int CONSTANT = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"var \"",
    "\"namespace \"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "<DOLLER>",
    "\"#\"",
    "\":\"",
    "\",\"",
    "\"\\\"\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "\";\"",
    "<QUOTED_STRING>",
    "\"\\\"\\\"\"",
    "<CONSTANT>",
    "<DIGIT>",
  };

}
